// src/components/login-form.tsx
"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { login } from "@/lib/api/auth";
import { cn } from "@/lib/utils";
import { useAuthStore } from "@/stores/useAuthStore";

export function LoginForm({
  className,
  ...props
}: React.ComponentProps<"div">) {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const setToken = useAuthStore((s) => s.setToken);
  const loadUser = useAuthStore((s) => s.loadUser);

  async function onSubmit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const form = new FormData(e.currentTarget);
    const email = String(form.get("email") || "");
    const password = String(form.get("password") || "");

    setLoading(true);
    try {
      const json = await login(email, password);
      const token = json.data?.token as string | undefined;
      if (!token) throw new Error("No token returned");
      setToken(token);
      // Eagerly load user profile for sidebar, etc.
      void loadUser();
      toast.success("Logged in");
      // Redirect back to the page the user originally wanted, if any.
      const redirect =
        window.sessionStorage.getItem("postLoginRedirect") || "/datasets";
      window.sessionStorage.removeItem("postLoginRedirect");
      router.push(redirect);
    } catch (err: unknown) {
      toast.error("Login failed", {
        description: err instanceof Error ? err.message : "Unknown error",
      });
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className={cn("flex flex-col gap-6", className)} {...props}>
      <Card>
        <CardHeader className="text-center">
          <CardTitle className="text-xl">Welcome back</CardTitle>
          <CardDescription>Login with your Brozz Admin account</CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={onSubmit}>
            <FieldGroup>
              <Field>
                <FieldLabel htmlFor="email">Email</FieldLabel>
                <Input
                  id="email"
                  name="email"
                  type="email"
                  placeholder="m@example.com"
                  required
                  disabled={loading}
                />
              </Field>
              <Field>
                <div className="flex items-center">
                  <FieldLabel htmlFor="password">Password</FieldLabel>
                  <a
                    href="/forgot-password"
                    className="ml-auto text-sm underline-offset-4 hover:underline"
                  >
                    Forgot your password?
                  </a>
                </div>
                <Input
                  id="password"
                  name="password"
                  type="password"
                  required
                  disabled={loading}
                />
              </Field>
              <Field>
                <Button type="submit" disabled={loading} size="lg" className="w-full">
                  {loading ? "Logging in..." : "Login"}
                </Button>
                <FieldDescription className="text-center">
                  Don&apos;t have an account? <a href="/signup">Sign up</a>
                </FieldDescription>
              </Field>
            </FieldGroup>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}

// src/lib/components/login-form.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { Button } from '$lib/components/ui/button/index.js';
	import * as Card from '$lib/components/ui/card/index.js';
	import { Field, FieldGroup, FieldLabel, FieldDescription } from '$lib/components/ui/field/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { cn } from '$lib/utils.js';
	import { login } from '$lib/api/auth.js';
	import { authStore } from '$lib/stores/auth.svelte.js';
	import { toast } from 'svelte-sonner';
	import type { HTMLAttributes } from 'svelte/elements';

	let { class: className, ...restProps }: HTMLAttributes<HTMLDivElement> = $props();

	let loading = $state(false);

	async function onSubmit(e: SubmitEvent) {
		e.preventDefault();
		const form = new FormData(e.currentTarget as HTMLFormElement);
		const email = String(form.get('email') || '');
		const password = String(form.get('password') || '');

		loading = true;
		try {
			const json = await login(email, password);
			const token = json.data?.token;
			if (!token) throw new Error('No token returned');
			authStore.setToken(token);
			void authStore.loadUser();
			toast.success('Logged in');
			const redirect =
				(typeof window !== 'undefined' && window.sessionStorage.getItem('postLoginRedirect')) || '/dashboard';
			if (typeof window !== 'undefined') window.sessionStorage.removeItem('postLoginRedirect');
			goto(redirect);
		} catch (err: unknown) {
			toast.error('Login failed', {
				description: err instanceof Error ? err.message : 'Unknown error',
			});
		} finally {
			loading = false;
		}
	}
</script>

<div class={cn('flex flex-col gap-6', className)} {...restProps}>
	<Card.Root>
		<Card.Header class="text-center">
			<Card.Title class="text-xl">Welcome back</Card.Title>
			<Card.Description>Login with your Brozz Admin account</Card.Description>
		</Card.Header>
		<Card.Content>
			<form onsubmit={onSubmit}>
				<FieldGroup>
					<Field>
						<FieldLabel for="email">Email</FieldLabel>
						<Input id="email" name="email" type="email" placeholder="m@example.com" required disabled={loading} />
					</Field>
					<Field>
						<div class="flex items-center">
							<FieldLabel for="password">Password</FieldLabel>
							<a href="/forgot-password" class="ms-auto text-sm underline-offset-4 hover:underline">
								Forgot your password?
							</a>
						</div>
						<Input id="password" name="password" type="password" required disabled={loading} />
					</Field>
					<Field>
						<Button type="submit" disabled={loading} size="lg" class="w-full">
							{loading ? 'Logging in...' : 'Login'}
						</Button>
						<FieldDescription class="text-center">
							Don't have an account? <a href="/signup">Sign up</a>
						</FieldDescription>
					</Field>
				</FieldGroup>
			</form>
		</Card.Content>
	</Card.Root>
</div>
